### ISSUE TITLE
Need to add build flavors to iOS

### ISSUE THREAD

**Issue by diarmaidlindsay** [monstar-lab-oss/flutter-template-riverpod#5]
https://docs.flutter.dev/deployment/flavors
![image](https://user-images.githubusercontent.com/11836011/196639716-40993265-4c86-422d-916d-5aa42e301e8e.png)

Verify with 
`flutter run --flavor development -t lib/main/main_development.dart` 
and
`flutter run --flavor production -t lib/main/main_production.dart`

**Comment by dinakar-m** [comment]
Got it will check

**Comment by dinakar-m** [comment]
done here
https://github.com/monstar-lab-oss/flutter-template-riverpod/pull/6
